"""Generate backend/_worker_embedded.py from backend/tts_worker.py."""
import base64
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
source = root / "backend" / "tts_worker.py"
output = root / "backend" / "_worker_embedded.py"
b64 = base64.b64encode(source.read_bytes()).decode("ascii")
output.write_text(
    "# Auto-generated by packaging/embed_worker.py; do not edit.\n"
    "TTS_WORKER_B64 = " + repr(b64) + "\n",
    encoding="utf-8",
)
print("embedded worker bytes:", len(b64))
